name: smartcue
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  hive: ^2.2.3
  another_flushbar: ^1.12.30
  get_it: ^8.0.3
  drop_down_list: ^2.0.0
  auto_scroll_text: ^0.0.7
  path_provider: ^2.1.5
  pdf: ^3.11.2
  teleprompter: ^0.1.1
  uuid: ^4.5.1
  awesome_dialog: ^3.2.1
  dio: ^5.7.0
  shared_preferences: ^2.4.0
  flashy_tab_bar2: ^0.0.10
  go_router: ^14.7.1
  google_generative_ai: ^0.4.6
  permission_handler: ^11.3.1
  file_picker: ^8.1.7
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1


flutter:

 
  uses-material-design: true

 
  assets:
    - .env
    - assets/images/
  

 

 
  fonts:
    - family: Gummy
      fonts:
        - asset: assets/fonts/Gummy.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Zain
      fonts:
        - asset: assets/fonts/Zain.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
